name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust (nightly-2025-08-14)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2025-08-14
          override: true
          profile: minimal

      - name: Run tests
        run: cargo test --package prover --test test
